[[local|localrc]]
ADMIN_PASSWORD=000000
DATABASE_PASSWORD=000000
RABBIT_PASSWORD=000000
SERVICE_PASSWORD=000000
GIT_BASE=http://git.trystack.cn
NOVNC_REPO=http://git.trystack.cn/kanaka/noVNC.git
SPICE_REPO=http://git.trystack.cn/git/spice/spice-html5.git
DOWNLOAD_DEFAULT_IMAGES=False
IMAGE_URLS=http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
HOST_IP=192.168.0.14
SERVICE_IP_VERSION=4
FIXED_RANGE=10.0.0.0/24
FLOATING_RANGE=192.168.111.0/24
PUBLIC_INTERFACE=ens8
PUBLIC_NETWORK_GATEWAY=192.168.111.1
disable_service n-net
enable_service q-svc
disable_service q-agt
enable_service q-dhcp
disable_service q-l3
enable_service q-meta
enable_service q-metering
enable_service neutron