[tox]
minversion = 3.1.1
envlist = py36,functional,pep8
skipsdist = True

[testenv]
usedevelop = True
# tox is silly... these need to be separated by a newline....
whitelist_externals = bash
                      find
                      rm
install_command = pip install -r {toxinidir}/requirements.txt {opts} {packages}
setenv = VIRTUAL_ENV={envdir}
         LANGUAGE=en_US
         LC_ALL=en_US.utf-8
commands =
  find ./cbok -type f -name "*.pyc" -delete
passenv = http_proxy HTTP_PROXY https_proxy HTTPS_PROXY no_proxy NO_PROXY

[testenv:py36]
basepython = python3.6
commands =
  {[testenv]commands}
  stestr run {posargs}
  stestr slowest

[testenv:functional]
basepython = python3.6
setenv = {[testenv]setenv}
deps =
  -r{toxinidir}/test-requirements.txt
commands =
  stestr run --test-path=./cbok/tests/functional --serial {posargs}
  stestr slowest

[testenv:pep8]
basepython = python3.6
deps = hacking
commands =
  bash tools/flake8wrap.sh {posargs}

[testenv:cover]
basepython = python3.6
setenv =
    PYTHON=coverage run --include=cbok/* --omit=cbok/tests/functional --parallel-mode --concurrency=eventlet
commands =
    coverage erase
    stestr run '{posargs}'
    coverage combine
    coverage html --include='cbok/*' --omit='cbok/tests/unit/*' -d cover -i
    coverage report -m
